"""Add Slider  Model.

Revision ID: 3f3426809feb
Revises: 8cd2a79c2cc4
Create Date: 2024-06-01 09:42:16.420590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3426809feb'
down_revision = '8cd2a79c2cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slider_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('cludinaryId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slider_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cludinaryId', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('url')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
